server:
  port:8080
servlet:
  context-path:/

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_huazp_mall_v3?serverTimezone=Asia/Shanghai
    username: root
    password: Admin@123

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false # 开启驼峰功能
    auto-mapping-behavior: full # 自动映射任何复杂的结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxea3b0511f5108815
  secret: 1ef0ac3e9106f276d2441494cc136dac


weixinpayconfig:
  appid: wxf503a70f5f45cbd2
  mch_id: 1500625891
  key: jrBXpyMVPNY0FCFI42EBShLom7KMaRBa
  url: https://api.mch.weixin.qq.com/pay/unifiedorder
  notify_url: https://2c23-222-184-165-54.ngrok.io/weixinpay/notifyUrl